---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	start(start)
	analyze_input(analyze_input)
	call_tool(call_tool)
	generate_response(generate_response)
	end(end)
	__end__([<p>__end__</p>]):::last
	__start__ --> start;
	analyze_input -. &nbsp;need&nbsp; .-> call_tool;
	analyze_input -. &nbsp;no_need&nbsp; .-> generate_response;
	call_tool --> generate_response;
	generate_response --> end;
	start --> analyze_input;
	end --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
